### PR TITLE
Pricing

### PR DESCRIPTION
**Pull request by mikemcalister**

### CODE REVIEW

**Comment by dreamwhisper** [comment]
@mikemcalister When alignwide is selected, the width of the Pricing table block in the admin is the same as the standard. I'm not seeing `data-align="wide"` on the outer div.

**Comment by mikemcalister** [comment]
@dreamwhisper Nice catch, Jen! Fixed.

**Comment by nickcernis** [comment]
Width fix looks good.

**Comment by nickcernis** [comment]
@mikemcalister This is looking good!

The “convert to ordered list” product description component toolbar button has no effect for me:

edit_page_ _dev_with_a_title_that_is_longer_than_the_average_site_ _wordpress

The console produces “onTagNameChange is not a function” when clicking that button. Guessing an `onTagNameChange` prop for the description component?

https://github.com/ArrayHQ/atomic-blocks/blob/5cbdca652d9d05b32ce35e5e209ef67979ab73ba/src/blocks/block-pricing-table-inner/components/description/edit.js#L66-L76

**Comment by mikemcalister** [comment]
@nickcernis I was trying to track this down last night, good find! I'm actually not even getting the convert list buttons on my table for some reason. @dreamwhisper do you have this convert list button as well?

no list

**Comment by dreamwhisper** [comment]
@mikemcalister Yes, I also have the convert button.

**Comment by mikemcalister** [comment]
I made a lot of fixes based on the feedback @dreamwhisper added in the UX doc! Thanks for that! I had a few hesitations about: 

- Global color option. As mentioned in the doc, this requires more heavy-handed CSS than I'd like to add and would like to avoid it if possible. Going to do a few tests on this again to confirm.
- Box shadow. I think the border options we have in there are a good start. Adding box shadow requires another 4 or 5 settings and color pickers (opacity, size, spread, color) and I'd like to keep the options in check. 

I covered just about everything else in fixes seen in the commits above. Keep the feedback coming!

**Comment by nickcernis** [comment]
@mikemcalister @dreamwhisper Should the component title and description be changed to reflect the change from Pricing Table to Pricing Column too?

screenshot 2019-02-07 at 11 54 31

**Comment by dreamwhisper** [comment]
@nickcernis @mikemcalister If we can change that when a block is selected like it does with the inner blocks, it would be another indicator what you are customizing.

**Comment by dreamwhisper** [comment]
One thing I noticed is the Product Title Focus color is not the selected custom color.

color
focus-color

**Comment by mikemcalister** [comment]
Core has some really odd choice styling for that focus state. Fixed!

**Pull request merged**
